"""Initial schema migration

Revision ID: 8c0c5d2ce1fc
Revises: 
Create Date: 2026-10-04 17:59:47.987883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c0c5d2ce1fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('target_feature', sa.String(length=128), nullable=False),
    sa.Column('model_engine', sa.String(length=64), nullable=False),
    sa.Column('pricing_mode', sa.String(length=32), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('thinking_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('estimated_savings_usd', sa.Float(), nullable=False),
    sa.Column('effective_rate_per_1k', sa.Float(), nullable=False),
    sa.Column('alert_level', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_records_created_at'), 'cost_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_cost_records_mission_id'), 'cost_records', ['mission_id'], unique=False)
    op.create_table('gateway_model_providers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider_type', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gateway_model_quotas',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('max_monthly_spend_usd', sa.Float(), nullable=False),
    sa.Column('max_daily_spend_usd', sa.Float(), nullable=False),
    sa.Column('max_requests_per_minute', sa.Integer(), nullable=False),
    sa.Column('current_month_spend_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gateway_model_quotas_organization_id'), 'gateway_model_quotas', ['organization_id'], unique=True)
    op.create_table('gateway_model_usage',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('provider_type', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gateway_model_usage_created_at'), 'gateway_model_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_gateway_model_usage_mission_id'), 'gateway_model_usage', ['mission_id'], unique=False)
    op.create_index(op.f('ix_gateway_model_usage_model_name'), 'gateway_model_usage', ['model_name'], unique=False)
    op.create_index(op.f('ix_gateway_model_usage_organization_id'), 'gateway_model_usage', ['organization_id'], unique=False)
    op.create_index(op.f('ix_gateway_model_usage_project_id'), 'gateway_model_usage', ['project_id'], unique=False)
    op.create_index(op.f('ix_gateway_model_usage_user_id'), 'gateway_model_usage', ['user_id'], unique=False)
    op.create_table('mission_diffs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('diff_content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('comments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_diffs_mission_id'), 'mission_diffs', ['mission_id'], unique=False)
    op.create_table('mission_permission_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('directory', sa.String(length=512), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('granted_scope', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_permission_requests_mission_id'), 'mission_permission_requests', ['mission_id'], unique=False)
    op.create_table('mission_selections',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('recommended_option', sa.String(length=64), nullable=True),
    sa.Column('selected_option', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_selections_mission_id'), 'mission_selections', ['mission_id'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_phase', sa.String(length=64), nullable=False),
    sa.Column('execution_policy', sa.JSON(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_created_at'), 'missions', ['created_at'], unique=False)
    op.create_index(op.f('ix_missions_status'), 'missions', ['status'], unique=False)
    op.create_table('security_agents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_agents_device_id'), 'security_agents', ['device_id'], unique=False)
    op.create_index(op.f('ix_security_agents_project_id'), 'security_agents', ['project_id'], unique=False)
    op.create_table('security_audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('mission_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_audit_events_action'), 'security_audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_security_audit_events_actor_id'), 'security_audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_security_audit_events_mission_id'), 'security_audit_events', ['mission_id'], unique=False)
    op.create_index(op.f('ix_security_audit_events_organization_id'), 'security_audit_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_security_audit_events_project_id'), 'security_audit_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_security_audit_events_request_id'), 'security_audit_events', ['request_id'], unique=False)
    op.create_index(op.f('ix_security_audit_events_timestamp'), 'security_audit_events', ['timestamp'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_actor_id'), 'security_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_timestamp'), 'security_events', ['timestamp'], unique=False)
    op.create_table('security_organizations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('tier', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_organizations_slug'), 'security_organizations', ['slug'], unique=True)
    op.create_table('security_users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_users_created_at'), 'security_users', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_users_email'), 'security_users', ['email'], unique=True)
    op.create_index(op.f('ix_security_users_tenant_id'), 'security_users', ['tenant_id'], unique=False)
    op.create_table('gateway_model_credentials',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=False),
    sa.Column('secret_reference', sa.String(length=512), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_rotated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['gateway_model_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gateway_model_credentials_provider_id'), 'gateway_model_credentials', ['provider_id'], unique=False)
    op.create_table('gateway_registered_models',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model_identifier', sa.String(length=256), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_per_1k_input', sa.Float(), nullable=False),
    sa.Column('cost_per_1k_output', sa.Float(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['gateway_model_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gateway_registered_models_name'), 'gateway_registered_models', ['name'], unique=True)
    op.create_index(op.f('ix_gateway_registered_models_provider_id'), 'gateway_registered_models', ['provider_id'], unique=False)
    op.create_table('mission_artifacts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_artifacts_mission_id'), 'mission_artifacts', ['mission_id'], unique=False)
    op.create_table('mission_checkpoints',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('phase', sa.String(length=64), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_checkpoints_mission_id'), 'mission_checkpoints', ['mission_id'], unique=False)
    op.create_table('mission_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('causation_id', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_events_event_type'), 'mission_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_mission_events_mission_id'), 'mission_events', ['mission_id'], unique=False)
    op.create_index(op.f('ix_mission_events_sequence'), 'mission_events', ['sequence'], unique=False)
    op.create_table('mission_messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_messages_mission_id'), 'mission_messages', ['mission_id'], unique=False)
    op.create_table('mission_plans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_plans_mission_id'), 'mission_plans', ['mission_id'], unique=False)
    op.create_table('security_projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['security_organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_projects_organization_id'), 'security_projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_security_projects_slug'), 'security_projects', ['slug'], unique=False)
    op.create_table('security_user_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('session_token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_info', sa.String(length=256), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['security_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_user_sessions_session_token_hash'), 'security_user_sessions', ['session_token_hash'], unique=False)
    op.create_index(op.f('ix_security_user_sessions_user_id'), 'security_user_sessions', ['user_id'], unique=False)
    op.create_table('mission_attachments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_reference', sa.String(length=512), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['mission_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_attachments_mission_id'), 'mission_attachments', ['mission_id'], unique=False)
    op.create_index(op.f('ix_mission_attachments_sha256_hash'), 'mission_attachments', ['sha256_hash'], unique=False)
    op.create_table('security_refresh_tokens',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=64), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['security_user_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_refresh_tokens_family_id'), 'security_refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_security_refresh_tokens_session_id'), 'security_refresh_tokens', ['session_id'], unique=False)
    op.create_index(op.f('ix_security_refresh_tokens_token_hash'), 'security_refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_security_refresh_tokens_user_id'), 'security_refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_refresh_tokens_user_id'), table_name='security_refresh_tokens')
    op.drop_index(op.f('ix_security_refresh_tokens_token_hash'), table_name='security_refresh_tokens')
    op.drop_index(op.f('ix_security_refresh_tokens_session_id'), table_name='security_refresh_tokens')
    op.drop_index(op.f('ix_security_refresh_tokens_family_id'), table_name='security_refresh_tokens')
    op.drop_table('security_refresh_tokens')
    op.drop_index(op.f('ix_mission_attachments_sha256_hash'), table_name='mission_attachments')
    op.drop_index(op.f('ix_mission_attachments_mission_id'), table_name='mission_attachments')
    op.drop_table('mission_attachments')
    op.drop_index(op.f('ix_security_user_sessions_user_id'), table_name='security_user_sessions')
    op.drop_index(op.f('ix_security_user_sessions_session_token_hash'), table_name='security_user_sessions')
    op.drop_table('security_user_sessions')
    op.drop_index(op.f('ix_security_projects_slug'), table_name='security_projects')
    op.drop_index(op.f('ix_security_projects_organization_id'), table_name='security_projects')
    op.drop_table('security_projects')
    op.drop_index(op.f('ix_mission_plans_mission_id'), table_name='mission_plans')
    op.drop_table('mission_plans')
    op.drop_index(op.f('ix_mission_messages_mission_id'), table_name='mission_messages')
    op.drop_table('mission_messages')
    op.drop_index(op.f('ix_mission_events_sequence'), table_name='mission_events')
    op.drop_index(op.f('ix_mission_events_mission_id'), table_name='mission_events')
    op.drop_index(op.f('ix_mission_events_event_type'), table_name='mission_events')
    op.drop_table('mission_events')
    op.drop_index(op.f('ix_mission_checkpoints_mission_id'), table_name='mission_checkpoints')
    op.drop_table('mission_checkpoints')
    op.drop_index(op.f('ix_mission_artifacts_mission_id'), table_name='mission_artifacts')
    op.drop_table('mission_artifacts')
    op.drop_index(op.f('ix_gateway_registered_models_provider_id'), table_name='gateway_registered_models')
    op.drop_index(op.f('ix_gateway_registered_models_name'), table_name='gateway_registered_models')
    op.drop_table('gateway_registered_models')
    op.drop_index(op.f('ix_gateway_model_credentials_provider_id'), table_name='gateway_model_credentials')
    op.drop_table('gateway_model_credentials')
    op.drop_index(op.f('ix_security_users_tenant_id'), table_name='security_users')
    op.drop_index(op.f('ix_security_users_email'), table_name='security_users')
    op.drop_index(op.f('ix_security_users_created_at'), table_name='security_users')
    op.drop_table('security_users')
    op.drop_index(op.f('ix_security_organizations_slug'), table_name='security_organizations')
    op.drop_table('security_organizations')
    op.drop_index(op.f('ix_security_events_timestamp'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_actor_id'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_security_audit_events_timestamp'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_request_id'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_project_id'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_organization_id'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_mission_id'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_actor_id'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_action'), table_name='security_audit_events')
    op.drop_table('security_audit_events')
    op.drop_index(op.f('ix_security_agents_project_id'), table_name='security_agents')
    op.drop_index(op.f('ix_security_agents_device_id'), table_name='security_agents')
    op.drop_table('security_agents')
    op.drop_index(op.f('ix_missions_status'), table_name='missions')
    op.drop_index(op.f('ix_missions_created_at'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_mission_selections_mission_id'), table_name='mission_selections')
    op.drop_table('mission_selections')
    op.drop_index(op.f('ix_mission_permission_requests_mission_id'), table_name='mission_permission_requests')
    op.drop_table('mission_permission_requests')
    op.drop_index(op.f('ix_mission_diffs_mission_id'), table_name='mission_diffs')
    op.drop_table('mission_diffs')
    op.drop_index(op.f('ix_gateway_model_usage_user_id'), table_name='gateway_model_usage')
    op.drop_index(op.f('ix_gateway_model_usage_project_id'), table_name='gateway_model_usage')
    op.drop_index(op.f('ix_gateway_model_usage_organization_id'), table_name='gateway_model_usage')
    op.drop_index(op.f('ix_gateway_model_usage_model_name'), table_name='gateway_model_usage')
    op.drop_index(op.f('ix_gateway_model_usage_mission_id'), table_name='gateway_model_usage')
    op.drop_index(op.f('ix_gateway_model_usage_created_at'), table_name='gateway_model_usage')
    op.drop_table('gateway_model_usage')
    op.drop_index(op.f('ix_gateway_model_quotas_organization_id'), table_name='gateway_model_quotas')
    op.drop_table('gateway_model_quotas')
    op.drop_table('gateway_model_providers')
    op.drop_index(op.f('ix_cost_records_mission_id'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_created_at'), table_name='cost_records')
    op.drop_table('cost_records')
    # ### end Alembic commands ###
