"""
Reviewer Role
=============
Critiques and validates implementation plans generated by the Planner before any code is modified.
Checks for scope violations, architectural rule adherence, and token budget compliance.
"""

from typing import Any

from app.modules.agent.roles.base import AgentRole, PlanOutput

REVIEWER_SYSTEM_PROMPT = """You are the Senior Architectural Reviewer Agent for the repository intelligence engine powered by NVIDIA Nemotron 3 Ultra.
Your objective:
1. Review the proposed implementation plan critically before any code is generated or edited.
2. Check for scope sprawl: reject plans attempting to touch files outside the targeted feature.
3. Check for architectural violations: cyclic dependencies, anti-patterns, missing tests, or breaking contracts.
4. If the plan is sound, approve it explicitly. If defective, provide constructive corrections.
"""


class ReviewerRole(AgentRole):
    """Specialized agent role for architectural critique and plan authorization."""

    def __init__(self):
        super().__init__(
            name="Reviewer",
            system_prompt=REVIEWER_SYSTEM_PROMPT,
            allowed_tools=["read_file", "search_code"],
        )

    def build_system_message(self) -> dict[str, str]:
        return {"role": "system", "content": self.system_prompt}

    def build_context_prompt(
        self, goal: str, context: dict[str, Any]
    ) -> list[dict[str, str]]:
        plan: PlanOutput = context.get("plan")
        arch_rules = context.get("architecture_rules", "No rules configured.")

        plan_summary = (
            f"Summary: {plan.summary}\nPrimary Files: {plan.primary_files}\nTest Files: {plan.test_files}"
            if plan
            else "No plan provided."
        )

        user_content = f"""## Mission Goal:
{goal}

## Proposed Plan to Review:
{plan_summary}

## Repository Architectural Rules:
{arch_rules}

Critique this plan. State whether it is APPROVED or REJECTED.
List any scope violations, risks, or required modifications.
"""
        return [
            self.build_system_message(),
            {"role": "user", "content": user_content},
        ]
